server:
  port: 8081

spring:
  application:
    name: gateway1
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: on
              lower-case-service-id: on
eureka:
  client:
    service-url:
      defaultZone: http://172.21.72.154:8900/eureka/
    register-with-eureka: true
    fetch-registry: true