server:
  port: 8082
spring:
  application:
    name: gateway2
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
logging:
  level:
    io.jcz: debug